# Generated by Django 2.2.12 on 2022-06-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('freeze_id', models.CharField(max_length=50, null=True)),
                ('device_Name', models.CharField(max_length=100, null=True, unique=True)),
                ('organization', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'device',
            },
        ),
    ]
