# Generated by Django 4.0.5 on 2022-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
