# Generated by Django 2.2.12 on 2022-06-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='registration_data',
            field=models.DateField(auto_now=True),
        ),
    ]
