# Generated by Django 2.2.12 on 2022-06-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_device_registration_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='registration_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
